Vagrant.configure("2") do |config|
  # Loop para criar 4 máquinas virtuais
  (0..3).each do |i|
    config.vm.define "vm#{i}" do |node|
      node.vm.box = "ubuntu/focal64"
      node.vm.network "public_network", ip: "192.168.0.#{204 + i}"
      
      # Configurações específicas do VirtualBox
      node.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = "1"
        if i == 0
          vb.name = "master" 
        else 
          vb.name = "node#{'%02d' % i}"
        end
      end

      node.vm.boot_timeout = 1000 

      if i == 0
        node.vm.provision "shell", path: "config-server-ubuntu.sh", args: "master"
      else   
        node.vm.provision "shell", path: "config-server-ubuntu.sh", args: "node#{'%02d' % i}"  
      end
    end
  end
end